### ISSUE TITLE
Host/Code is wrong.

### ISSUE THREAD

**Issue by GeoBenJi** [fuatakgun/bwt_perla#1]
Hi,
tried to establish a connection from Home Assistant (HACS integration) to my Perla Home. Got error message "Host/Code is wrong." after submitting the required information.

I took the Code from E-Mail I received after registration (login code).

BR

**Comment by fuatakgun** [comment]
Hey, welcome, can you try to access host over browser and login with the code you have received?

**Comment by GeoBenJi** [comment]
Yes, that works perfectly fine.

**Comment by fuatakgun** [comment]
Just to be sure that we have the same device. Adding my login and main screens, can you also post yours?

![Screenshot_2021-09-29-20-23-56-408_com.android.chrome.jpg](https://user-images.githubusercontent.com/11085566/135327065-bb79a980-b85f-43b5-afc5-ea8ef5a32bbe.jpg)

![Screenshot_2021-09-29-20-23-38-683_com.android.chrome.jpg](https://user-images.githubusercontent.com/11085566/135327072-b65c4548-8cbd-45c4-89b9-6d7a30ab5900.jpg)

**Comment by GeoBenJi** [comment]
The behaviour of the web interface seems very weird. Most of the times I connected over IP I just saw the menu where I can adjust the water quality. After several more tries I finally see the main menu (dashboard). However connection through HA isn't possible at all. Maybe a firmware update of the device is required. What kind of model do you have on what firmware version?

**Comment by fuatakgun** [comment]
Let me share some screenshots. I am also able to use official mobile app to connect to device.



![Screenshot_2021-10-03-23-44-17-264_com.android.chrome.jpg](https://user-images.githubusercontent.com/11085566/135772499-179f8138-577d-4a23-85b6-9412dc7370a2.jpg)

![Screenshot_2021-10-03-23-44-50-437_com.android.chrome~2.jpg](https://user-images.githubusercontent.com/11085566/135772540-d365e7f5-197a-4f72-9f98-a043e6c64a19.jpg)

![Screenshot_2021-10-03-23-46-42-314_com.bwt.athomeapp.jpg](https://user-images.githubusercontent.com/11085566/135772563-4c8bb8a5-bf8c-4f70-b875-83b5a4d389e6.jpg)

![Screenshot_2021-10-03-23-47-05-638_com.bwt.athomeapp.jpg](https://user-images.githubusercontent.com/11085566/135772572-b6383968-419a-4fd4-943d-02f2567a02a5.jpg)

**Comment by GeoBenJi** [comment]
@fuatakgun any news?

**Comment by fuatakgun** [comment]
Sorry, your setup is completely different than mine, vnc server makes things very complicated, this integration cannot work on your machine.
