### ISSUE TITLE
maintenance of bwt perla

### ISSUE THREAD

**Issue by bernji** [fuatakgun/bwt_perla#2]
Hi,

[feature request] Is it possible to get an entity when there is a maintenance (every 6 month) todo or when the salt is <= 20%?
I am able to see this in the notifications and the light turns yellow on the maschine. 
I am just curious if this is able to read through the API.

Thanks
Bernhard

**Comment by fuatakgun** [comment]
Yes possible, i will check this.

**Comment by fuatakgun** [comment]
now, there is a sensor called `sensor.regenerative_remaining_percentage` and you can setup automation with this.

There is another user contributed to fetch warnings, I will try to work on exposing this into HA.
