### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by PepeVegas** [fuatakgun/bwt_perla#5]
Hopefully it is allowed to ask questions here. I would need help please. 
I have added the IP address and the code under /config/custom_components/bwt_perla/translations/de.json. Now how do I get further to my entities? Please, best thanks.

**Comment by fuatakgun** [comment]
Have you read the readme file? You should use HACS to install this and use integrations page to set up in your home assistant.

**Comment by PepeVegas** [comment]
Of course I had read everything. Unfortunately I was on the line, but now I understand. Thank you very much! Now it is very easy.
